server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Quiz
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
